apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-html
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
    <meta charset="UTF-8">
    <title>Frontend</title>
    <style>
      body {
        font-size: 200x;
        font-family: Arial, sans-serif;
      }
    </style>
    </head>
    <body>
      This is Frontend
    </body>
    </html>
